name: maskanismarthome
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^3.2.0
  http: ^0.12.0+4
  equatable: ^1.1.1
  intl: ^0.16.1
  horizontal_picker: ^1.0.0
  flutter_dotenv: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.7
  uuid: ^2.0.4
  sweetalert: any
  flutter_swiper: ^1.1.6
  flutter_picker: ^1.1.5
  flutter_circular_slider: ^2.5.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  carousel_slider: ^2.2.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Welcome_Background@2x.png
    - assets/Logo@2x.png
    - assets/avatar@2x.png
    - assets/im_home.png
    - assets/im_out.png
    - assets/sleep.png
    - assets/wake_up.png
    - assets/living_room.png
    - assets/bed_room.png
    - assets/kitchen.png
    - assets/office.png
    - assets/settings.png
    - assets/timer.png
    - assets/temperature.png
    - assets/light.png
    - assets/curtains.png
    - assets/power.png
    - assets/loader.gif
    - assets/temperature_bg.png
    - assets/lights_bg.png
    - assets/window_bg.png
    - assets/Power_Outlets_bg.png
    - assets/text_background.png
    - .env
#     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Black.ttf
          weight: 900
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 800
        - asset: fonts/TitilliumWeb-SemiBold.ttf
          weight: 700
        - asset: fonts/TitilliumWeb-Regular.ttf
          weight: 400
        - asset: fonts/TitilliumWeb-Light.ttf
          weight: 300
        - asset: fonts/TitilliumWeb-ExtraLight.ttf
          weight: 100
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
